version: '3.7'

# Set a project name for the composition to use
name: $COMPOSE_PROJECT_NAME

# Services/Containers to orchestrate in this composition
services:

  # Basic PHP 5.6 CLI Image Container
  php-5-6-cli:
    container_name: ${PHP56_CLI_DOCKER_BOX}
    tty: true
    restart: unless-stopped
    image: ${PHP56_CLI_DOCKER_IMAGE}:${PHP56_CLI_DOCKER_IMAGE_TAG}
    environment:
        - APP_ENV=${APP_ENV}
    working_dir: /var/www
    volumes:
      - ./public_html:/var/www/html
#      - ./docker-files/php/56.local.ini:/usr/local/etc/php.ini
    networks:
      - web-app-network

# Custom network for composed containers to communicate on
networks:
  web-app-network:
    driver: bridge

